### ISSUE TITLE
Vote for Org logo

### ISSUE THREAD

**Issue by ParthS007** [yogdaan/Artworks#1]
add your pull with single logo and with thumbs :+1:  or thumbs down :-1:  we can decide the logo

**Comment by gabru-md** [comment]
It will be better to first comment down the logos, and then have a voting on the comments. Finally, only the chosen one will send a PR ?

**Comment by ParthS007** [comment]
It will take time to make logo with Indian Touch, will send PR as soon as logo is final :+1:

**Comment by ParthS007** [comment]
![whatsapp image 2018-04-05 at 11 52 44 pm](https://user-images.githubusercontent.com/24358501/38406110-2993986e-3991-11e8-8b14-b7a13402d68f.jpeg)

**Comment by ParthS007** [comment]
![whatsapp image 2018-04-06 at 12 29 44 am](https://user-images.githubusercontent.com/24358501/38406131-3e1c79ae-3991-11e8-9e9f-489ea72ce2ec.jpeg)

**Comment by ParthS007** [comment]
![photo6210534126495311917](https://user-images.githubusercontent.com/24358501/38406265-cffbc51e-3991-11e8-835b-7c155edd476b.jpg)

**Comment by ParthS007** [comment]
![photo6210534126495311918](https://user-images.githubusercontent.com/24358501/38406270-d6683ce8-3991-11e8-966e-ceda668c64f1.jpg)

**Comment by ParthS007** [comment]
![photo6210534126495311919](https://user-images.githubusercontent.com/24358501/38406275-dd758fa4-3991-11e8-905b-d57faefc6e35.jpg)

**Comment by ParthS007** [comment]
![photo6210534126495311920](https://user-images.githubusercontent.com/24358501/38406280-e27ac42e-3991-11e8-9569-02fc41233db4.jpg)

**Comment by ParthS007** [comment]
![photo6210534126495311921](https://user-images.githubusercontent.com/24358501/38406284-e7cfabb0-3991-11e8-9df8-d01f0522fd79.jpg)

**Comment by Ananthavijay** [comment]
![screenshot - 4_6_2018 2_13_05 pm](https://user-images.githubusercontent.com/35162705/38408900-f8836856-399c-11e8-978b-828a777c4c57.png)

**Comment by Ananthavijay** [comment]
![logo](https://user-images.githubusercontent.com/35162705/38419728-1fd33658-39bf-11e8-93e0-ee45fe8782df.png)

**Comment by gabru-md** [comment]
After voting, this image has been chosen as the final image.

![image](https://user-images.githubusercontent.com/25414121/38432273-92705e8c-39e4-11e8-9702-7ab10e351f8f.png)


But, is it not bent a bit towards the orange side ? Or is it just who thinks this looks a bit tilted?

**Comment by gabru-md** [comment]
Add this logo to the artwork repo as well. 
@ParthS007
